/*
 * CloudSim Plus: A modern, highly-extensible and easier-to-use Framework for
 * Modeling and Simulation of Cloud Computing Infrastructures and Services.
 * http://cloudsimplus.org
 *
 *     Copyright (C) 2015-2021 Universidade da Beira Interior (UBI, Portugal) and
 *     the Instituto Federal de Educação Ciência e Tecnologia do Tocantins (IFTO, Brazil).
 *
 *     This file is part of CloudSim Plus.
 *
 *     CloudSim Plus is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     CloudSim Plus is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with CloudSim Plus. If not, see <http://www.gnu.org/licenses/>.
 */
package org.cloudsimplus.services;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;
import org.cloudsimplus.cloudlets.Cloudlet;
import org.cloudsimplus.vms.Vm;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * One node of a {@link ServiceRequest}'s call graph.
 *
 * <p>A call says <i>"invoke {@link #getService() service S}, run {@link #getLengthBeforeCalls()}
 * MI of work on it, then synchronously call each child in turn, then run {@link #getLengthAfterCalls()}
 * MI of post-processing, and return"</i>.
 * Children are executed sequentially (typical synchronous-RPC microservice pattern).</p>
 *
 * <p>The exact same {@link Service} can appear at any depth, so chains like
 * {@code A -> B -> A -> D -> E} are naturally expressed by reusing the same
 * Service reference in different {@link ServiceCall} nodes.</p>
 *
 * @since CloudSim Plus 9.0.0
 */
@Getter @Setter
public class ServiceCall {
    /**
     * Lifecycle phases of a {@link ServiceCall} as the broker drives it.
     */
    public enum State {
        /** Created but not yet fired. */
        PENDING,
        /** Pre-processing cloudlet is running on the target VM. */
        RUNNING_PRE,
        /** A child call has been dispatched and we're waiting for it to return. */
        WAITING_CHILD,
        /** Post-processing cloudlet is running on the target VM. */
        RUNNING_POST,
        /** Call (and its whole subtree) has finished. */
        COMPLETED
    }

    @NonNull
    private Service service;

    /** Pre-processing length (MI). Use 0 to skip the pre-cloudlet entirely. */
    private long lengthBeforeCalls;

    /** Post-processing length (MI). Use 0 to skip the post-cloudlet entirely. */
    private long lengthAfterCalls;

    /** Number of PEs every cloudlet generated by this call requires. */
    private long pesNumber = 1;

    /**
     * Bytes representing the request payload sent <i>to</i> this service
     * (mapped onto the pre-cloudlet's input file size).
     */
    private long requestBytes = 1;

    /**
     * Bytes representing the response payload sent <i>back from</i> this service
     * (mapped onto the post-cloudlet's output file size).
     */
    private long responseBytes = 1;

    /**
     * Optional network delay (in seconds) added before this call starts running on the target VM.
     * Useful to simulate inter-service network hops.
     */
    private double networkDelay;

    private final List<ServiceCall> children = new ArrayList<>();

    // --- runtime state, populated by the broker ---
    @Setter(AccessLevel.PACKAGE)
    private State state = State.PENDING;

    @Setter(AccessLevel.PACKAGE)
    private ServiceCall parent;

    @Setter(AccessLevel.PACKAGE)
    private ServiceRequest request;

    @Setter(AccessLevel.PACKAGE)
    private Vm assignedVm = Vm.NULL;

    @Setter(AccessLevel.PACKAGE)
    private Cloudlet preCloudlet = Cloudlet.NULL;

    @Setter(AccessLevel.PACKAGE)
    private Cloudlet postCloudlet = Cloudlet.NULL;

    @Setter(AccessLevel.PACKAGE)
    private int currentChildIndex = -1;

    @Setter(AccessLevel.PACKAGE)
    private double startTime = -1;

    @Setter(AccessLevel.PACKAGE)
    private double finishTime = -1;

    /**
     * Creates a call targeting the given service with the supplied workloads.
     *
     * @param service           the service to invoke
     * @param lengthBeforeCalls MI of work executed on {@code service} before invoking any children (>= 0)
     * @param lengthAfterCalls  MI of work executed on {@code service} after the last child returns (>= 0)
     */
    public ServiceCall(final Service service, final long lengthBeforeCalls, final long lengthAfterCalls) {
        if (service == null) {
            throw new IllegalArgumentException("service must not be null");
        }
        if (lengthBeforeCalls < 0 || lengthAfterCalls < 0) {
            throw new IllegalArgumentException("Call lengths must be >= 0");
        }
        this.service = service;
        this.lengthBeforeCalls = lengthBeforeCalls;
        this.lengthAfterCalls = lengthAfterCalls;
    }

    /**
     * Convenience constructor for a leaf call with no post-processing.
     */
    public ServiceCall(final Service service, final long lengthBeforeCalls) {
        this(service, lengthBeforeCalls, 0);
    }

    /**
     * Adds a child call to be invoked synchronously after the pre-processing of this call finishes.
     * Children are executed in the order they are added.
     *
     * @param child the child call to register
     * @return this call, to enable chaining
     */
    public ServiceCall addChild(@NonNull final ServiceCall child) {
        children.add(child);
        return this;
    }

    /**
     * @return an unmodifiable view of the registered children.
     */
    public List<ServiceCall> getChildren() {
        return Collections.unmodifiableList(children);
    }

    /**
     * @return {@code true} if this call has not been started by the broker yet.
     */
    public boolean isPending() {
        return state == State.PENDING;
    }

    /**
     * @return {@code true} once the whole subtree rooted here has completed.
     */
    public boolean isCompleted() {
        return state == State.COMPLETED;
    }

    /**
     * @return {@code true} if this call has no parent (i.e. it is the request entrypoint).
     */
    public boolean isRoot() {
        return parent == null;
    }

    /**
     * @return total wall-clock time (in seconds) the call took, including children;
     * a negative value if the call has not finished yet.
     */
    public double getElapsedTime() {
        if (startTime < 0 || finishTime < 0) {
            return -1;
        }
        return finishTime - startTime;
    }

    @Override
    public String toString() {
        return "ServiceCall[%s, pre=%d MI, post=%d MI, children=%d, state=%s]"
            .formatted(service.getName(), lengthBeforeCalls, lengthAfterCalls, children.size(), state);
    }
}
