:source-highlighter: highlightjs
:numbered:
:unsafe:

ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

= CloudSim Plus Documentation

This directory contains the sources to generate several different kinds of CloudSim Plus documentation.
You can browse the http://cloudsimplus.rtfd.io[online documentation here]. 

The documentation includes:

* FAQs and guides in https://en.wikipedia.org/wiki/ReStructuredText[reStructuredText (rst)] format to be published at http://cloudsimplus.rtfd.io[ReadTheDocs site];
* http://staruml.io[StarUML] project containing link:cloudsim-plus.staruml.mdj[UML diagrams];
* link:CloudSim-and-CloudSimPlus-Comparison.html[Side-by-Side comparison between CloudSim and CloudSim Plus java simulation scenarios] (online version available http://cloudsimplus.org/CloudSim-and-CloudSimPlus-Comparison.html[here]);
* link:cloudsim-plus-white-paper.pdf[White Paper] published at the https://eubrasilcloudforum.eu[EU/Brasil Cloud FORUM].
* link:presentation/index.html[Web Slides] presenting CloudSim Plus (online version available http://cloudsimplus.org/presentation/[here]).

== Building the reStructuredText files for the Documentation Site

To generate the http://sphinx-doc.org[Sphinx] documentation to read locally, considering you have python installed, you can execute `make install` to install the additional tools.

Ensure you have the following environments variables declared, since the python scripts use UTF-8 encoding:

[source,bash]
----
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

----

To build the documentation in html use:

[source,shell]
----
make html
----

After that, you can navigate the generated documentation locally by accessing the [_build](_build) directory.
To publish the updated documentation to ReadTheDocs site, just commit any changes (which don't include the _build directory) and push them to GitHub.